version: '3'
services:
  neo4j:
    image: neo4j:3.5.3
    env_file: .neo4j.env
    volumes:
      - ./volumes/neo4j_data:/data
      - ./volumes/neo4j_logs:/logs
  redis:
    image: redis:5.0.5
  web:
    build:
      context: .
      dockerfile: ./docker/genealogy.dockerfile
    command: npm start
    volumes:
      - .:/app
    ports:
      - 8080:443
    depends_on:
      - redis
      - neo4j
